### ISSUE TITLE
Améliorer présentation/IHM

### ISSUE THREAD

**Issue by QuentinJoder** [IssouProjects/PLD-Agile#144]
-Faire en sorte que tout le texte de chaque bouton soit visible en petite fenêtre. (ou placer infobulle)
-Corriger fautes d'orthographes

**Comment by TimotheeDurand** [comment]
Eyecandy: améliorer l'affichage pour l'ajout de livraison:
- blue highlight autour de la map pour que l'user comprenne qu'il faut cliquer dessus
- affichage icon (+) sur survol des livraison pour montrer à l'user où il doit clicker

**Comment by Raul6469** [comment]
Je crois qu'on peut fermer ça maintenant qu'on a merge #202 non ?

**Comment by TimotheeDurand** [comment]
le truc c'est qu'on pourra toujours améliorer l'IHM, alors cette issue n'a pas vraiment de sens

**Comment by TimotheeDurand** [comment]
tu peux fermer azy azy
