### ISSUE TITLE
Ne pas effacer les livraisons/plan après annulation chargement

### ISSUE THREAD

**Issue by Raul6469** [IssouProjects/PLD-Agile#204]
Lorsque des demandes de livraison sont chargées, et que l'on clique sur "Charger livraisons" et qu'on annule (par exemple après un misclick), toutes les livraisons sont supprimées. Ce serait bien de ne les effacer que lorsqu'un fichier valide a été importé

**Comment by AmosTrask** [comment]
Oui alors j'ai essayé, le pb est que l’exception est levé pendant l'appel du controleur au deserialisateur, et l'appel contient l'objet plan (qui doit être clear au préaable)

**Comment by AmosTrask** [comment]
Du coup jsais pas trop comment faire

**Comment by TimotheeDurand** [comment]
je pourrais gérer ça avec une boite de dialogue qui te renvoie un chemin d'accès, et null si le type clique sur annuler. Ce serait le controleur qui appelle cette boite de dialogue avec un état intermédiaire. Mais ça impliquerais de changer un peu le fonctionnement actuel...

**Comment by AmosTrask** [comment]
voilà j'avais pensé à çà aussi mais bcp trop de changement

**Comment by TimotheeDurand** [comment]
(°□°) bEaUcOuP tRoP (°□°)

**Comment by Raul6469** [comment]
C'est pas très urgent de toute manière

**Comment by AmosTrask** [comment]
nop mais çà fait un comportement dégueulasse
