### ISSUE TITLE
Afficher si durée trop longue pour plage horaire

### ISSUE THREAD

**Issue by TimotheeDurand** [IssouProjects/PLD-Agile#207]
Par exemple: si la livraison a pour heure d'arrivée 10:30, doit durer 10 minutes et que la plage horaire est de 10:20 à 10:35 => afficher le problème dans la liste

**Comment by Raul6469** [comment]
On peut fermer ça avec #224 non ?

**Comment by TimotheeDurand** [comment]
c'était l'idée
