### ISSUE TITLE
CU: Echanger 2 livraisons - partie vue

### ISSUE THREAD

**Issue by AmosTrask** [IssouProjects/PLD-Agile#214]

**Comment by TimotheeDurand** [comment]
je propose 3 trucs:

- bouton (up) et (down), qui montent / descendent une livraison d'un cran
- drag and drop
- clic sur la livraison à bouger Puis clic sur le nouvel emplacement dans la liste (comme pour ajouter une livraison)

**Comment by Raul6469** [comment]
Je vote pour ⬆️ et ⬇️ , il me semble que la prof avait parlé de cette manière de faire
