### ISSUE TITLE
Prévoir comportement liste commandes après chargement nouveau fichier

### ISSUE THREAD

**Issue by Raul6469** [IssouProjects/PLD-Agile#220]
Actuellement, lorsque l'on change de plan ou de demandes de livraison, la liste des commandes est maintenue, et on obtient des exceptions quand on essaie d'annuler ou refaire des commandes.

**Comment by TimotheeDurand** [comment]
Faut supprimer la liste au chargement

**Comment by TimotheeDurand** [comment]
EtatInit et EtatPlanCharge

**Comment by TimotheeDurand** [comment]
Dans les methodes chargerPlan et chargerLivraison
