### ISSUE TITLE
Revoir le timeout calcul tournée

### ISSUE THREAD

**Issue by Raul6469** [IssouProjects/PLD-Agile#240]
Le temps donné pour le timeout n'est pas réellement le temps de calcul
/cc @HexaHugoMartin

**Comment by TimotheeDurand** [comment]
je pense qu'on peut revoir le système de timeout completement si on met le TSP dans un thread

**Comment by AmosTrask** [comment]
Non

**Comment by AmosTrask** [comment]
Enfin on pourrait mais j'suis pas sûr qu'on ai le temps
