### ISSUE TITLE
Notifier l'utilisateur s'il arrive ou pas dans la plage horaire d'une livraison

### ISSUE THREAD

**Issue by Raul6469** [IssouProjects/PLD-Agile#83]

**Comment by TimotheeDurand** [comment]
Je ne comprend pas ce que ça veut dire.

"Notifier l'utilisateur s'il arrive ou pas dans la plage horaire d'une livraison"
ça veut dire lui signaler si certaines plages horaires sont invalides dans la tournée ?
ça veut dire lui signaler si la plage horaire de la livraison est invalide quand il en ajoute une ?
ça veut dire lui dire si la tournée est impossible à cause des plages horaires ?

détaillez pleaaaase :)

**Comment by AmosTrask** [comment]
Il faut notifier l'utilisateur si après un recalcul une plage horaire n'est plus respectée. Par exemple la livraison s'affiche en rouge dans la liste.

**Comment by TimotheeDurand** [comment]
ok, je regarderais ça demain aprem
