### ISSUE TITLE
Notifier l'utilisateur si l'algorithme ne peut pas calculer de tournée

### ISSUE THREAD

**Issue by Raul6469** [IssouProjects/PLD-Agile#84]

**Comment by AmosTrask** [comment]
C'était quoi çà exactement déjà ?

**Comment by TimotheeDurand** [comment]
Si l'algo ne peut pas calculer de tournée conciliant toutes les plages horaires non ?

**Comment by AmosTrask** [comment]
Le comportement actuel fait que la tournee se calcul bien et il y a un warning sur la/les plages horaires non respectées. On garde çà ?

**Comment by Raul6469** [comment]
C'était plutôt dans le cas où l'algorithme mettait trop de temps pour calculer l'itinéraire. On proposerait à l'utilisateur de recalculer en prenant plus de temps

**Comment by AmosTrask** [comment]
Il y a une autre issue pour çà :)
