### ISSUE TITLE
Suppression d'une livraison

### ISSUE THREAD

**Issue by Raul6469** [IssouProjects/PLD-Agile#85]
En tant qu’utilisateur, je veux supprimer manuellement une livraison.

## Précondition
La tournée à déjà été calculée

## Scénario principal

1. Clic sur bouton supprimer en regard de la vue textuelle de la livraison
2. Re-calcul chemin entre livraison précédente et livraison suivante ET mise à jour durée et horaires de passage des livraisons suivantes et affichage

_validé par les profs_

**Comment by AmosTrask** [comment]
Bon j'ai pas respecté le scénario. Je vais refaire xD.
