### ISSUE TITLE
Voir sens parcours sur le plan

### ISSUE THREAD

**Issue by Raul6469** [IssouProjects/PLD-Agile#94]
Flèches ou dégradé de couleurs, ou visualisation du parcours en synchronisation avec la vue textuelle

**Comment by TimotheeDurand** [comment]
Il faut absolument y réfléchir asap

**Comment by TimotheeDurand** [comment]
parce que ça va pas être une mince affaire

**Comment by Raul6469** [comment]
Closed in #260
